name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Скачиваем репозиторий

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Обновляем pip
          pip install -r requirements.txt  # Устанавливаем зависимости
          pip install pytest-html  # Устанавливаем плагин для HTML отчета

      - name: Run tests
        run: |
          pytest --html=report.html --self-contained-html  # Запуск тестов и создание отчета

      - name: Upload test report
        if: always()  # Загружаем отчет даже если тесты не прошли
        uses: actions/upload-artifact@v3
        with:
          name: test-report  # Имя артефакта
          path: report.html  # Путь к отчету

  deploy:
    needs: build  # Этот job выполняется только после успешного завершения job 'build'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Скачиваем репозиторий

      - name: Upload code artifact
        uses: actions/upload-artifact@v3
        with:
          name: source-code  # Имя артефакта
          path: .  # Загружаем весь исходный код
